import test from 'node:test';
import assert from 'node:assert/strict';

import {
    generateToken,
    verifyToken,
    generateRefreshToken,
    verifyRefreshToken,
    generateApiKey,
} from '../utils/jwt';

const samplePayload = {
    userId: 'user_001',
    username: 'testuser',
    role: 'agent',
};

// ─── generateToken ──────────────────────────────

test('generateToken returns a string', () => {
    const token = generateToken(samplePayload);
    assert.equal(typeof token, 'string');
    assert.ok(token.length > 0);
});

// ─── verifyToken ────────────────────────────────

test('verifyToken can decode a token generated by generateToken', () => {
    const token = generateToken(samplePayload);
    const decoded = verifyToken(token);
    assert.ok(decoded);
});

test('verifyToken payload contains userId, username, role', () => {
    const token = generateToken(samplePayload);
    const decoded = verifyToken(token);
    assert.equal(decoded.userId, 'user_001');
    assert.equal(decoded.username, 'testuser');
    assert.equal(decoded.role, 'agent');
});

// ─── verifyRefreshToken ─────────────────────────

test('verifyRefreshToken decodes refresh tokens', () => {
    const refreshToken = generateRefreshToken(samplePayload);
    const decoded = verifyRefreshToken(refreshToken);
    assert.equal(decoded.userId, 'user_001');
    assert.equal(decoded.username, 'testuser');
    assert.equal(decoded.role, 'agent');
});

test('verifyRefreshToken throws on a regular (non-refresh) token', () => {
    const regularToken = generateToken(samplePayload);
    assert.throws(() => {
        verifyRefreshToken(regularToken);
    }, /Invalid token type/);
});

// ─── generateApiKey ─────────────────────────────

test('generateApiKey starts with eld_ and has length 44', () => {
    const apiKey = generateApiKey();
    assert.ok(apiKey.startsWith('eld_'));
    assert.equal(apiKey.length, 44); // 'eld_' (4) + 40 random chars
});

test('generateApiKey returns unique values', () => {
    const key1 = generateApiKey();
    const key2 = generateApiKey();
    assert.notEqual(key1, key2);
});
