-- AlterTable
ALTER TABLE "Campaign"
ADD COLUMN "dialRatio" DOUBLE PRECISION NOT NULL DEFAULT 3.0,
ADD COLUMN "retryDelaySeconds" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN "maxConcurrentCalls" INTEGER NOT NULL DEFAULT 0;
